// Build (spec 9.7): injects config, prompts, code and settings into build/*.json and writes
// site/config.js. `npm run build -- --site-only` writes only site/config.js.
// The output contains secrets (the Slack webhook URL) and lives in build/, which is gitignored.
import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { parseArgs } from 'node:util';
import { loadConfig, loadPrompts } from './lib/config.mjs';
import { readEnv } from './lib/env.mjs';

const ROOT = new URL('../', import.meta.url);
const path = (relative) => fileURLToPath(new URL(relative, ROOT));
const read = (relative) => readFileSync(new URL(relative, ROOT), 'utf8').replace(/\r\n/g, '\n');

// The logic files each Code node needs (spec 5.1 step 3), keyed by entry file name.
const CODE_NODES = {
  'business-config': [],
  'clean-and-validate': ['validate'],
  'build-ai-request': ['ai'],
  'score-and-write-reply': ['ai', 'score', 'compose'],
  'fallback-reply': ['score', 'compose'],
  'write-slack-message': ['compose'],
  'build-sheet-row': ['row'],
  'format-error-alert': [],
};
const WORKFLOWS = { 'lead-responder': 'build/lead-responder.json', 'error-alerts': 'build/error-alerts.json' };

function requireEnv(env, keys) {
  const missing = keys.filter((key) => !(env[key] ?? '').trim());
  if (missing.length) throw new Error(`Missing in .env: ${missing.join(', ')}. Run npm run check:env.`);
}

function writeSiteConfig(env) {
  const endpoint = `${env.N8N_BASE_URL.replace(/\/+$/, '')}/webhook/lead-intake`;
  writeFileSync(path('site/config.js'), `// Generated by scripts/build.mjs from .env. Do not edit.\nwindow.LEAD_ENDPOINT = ${JSON.stringify(endpoint)};\n`);
  return endpoint;
}

// Replaces %%NAME%% tokens with a function so "$" in values is never treated as a pattern.
function replaceTokens(text, values) {
  return text.replace(/%%([A-Z0-9_]+)%%/g, (match, name) => (Object.prototype.hasOwnProperty.call(values, name) ? values[name] : match));
}

function inlineCode(entry, codeValues) {
  const logic = CODE_NODES[entry].map((file) => read(`src/logic/${file}.js`).replace(/^export /gm, ''));
  return replaceTokens([...logic, read(`src/n8n/${entry}.entry.js`)].join('\n'), codeValues);
}

// Walks every string in the parsed workflow (never raw text replacement on JSON, spec 9.7 step 4).
function mapStrings(value, fn) {
  if (typeof value === 'string') return fn(value);
  if (Array.isArray(value)) return value.map((item) => mapStrings(item, fn));
  if (value && typeof value === 'object') return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, mapStrings(v, fn)]));
  return value;
}

function syntaxCheck(name, code) {
  mkdirSync(path('build/check'), { recursive: true });
  const file = path(`build/check/${name}.mjs`);
  writeFileSync(file, `async function __node() {\n${code}\n}\n`);
  try {
    execFileSync(process.execPath, ['--check', file], { stdio: 'pipe' });
  } catch (err) {
    throw new Error(`Code node ${name} has a syntax error:\n${err.stderr.toString().trim()}`);
  }
}

// Failure drills (Phase 6): each one swaps a single setting for one that fails the way the real outage
// would, without touching any secret. A plain build (no drills) restores everything.
export const DRILLS = {
  'ai-down': (v) => { v.AI_URL = 'http://host.docker.internal:9/v1/messages'; },
  'email-down': (v, extra) => {
    if (!extra.drillSmtpId) throw new Error('email-down needs the drill SMTP credential (deploy.mjs creates it).');
    v.N8N_CRED_SMTP_ID = extra.drillSmtpId;
  },
  'slack-down': (v) => { v.SLACK_WEBHOOK_URL = 'http://host.docker.internal:9/slack-drill'; },
  'sheet-down': (v) => { v.GOOGLE_SHEET_ID = 'drill-sheet-that-does-not-exist'; },
};

export function build({ siteOnly = false, drills = [], drillSmtpId = '' } = {}) {
  const env = readEnv();
  requireEnv(env, ['N8N_BASE_URL']);
  const endpoint = writeSiteConfig(env);
  if (siteOnly) return { endpoint };

  const bridge = env.AI_MODE !== 'api';
  requireEnv(env, [
    'SITE_ORIGIN', 'SLACK_WEBHOOK_URL', 'GOOGLE_SHEET_ID', 'GOOGLE_SHEET_TAB', 'SENDER_EMAIL', 'BOOKING_URL',
    'N8N_CRED_SMTP_ID', 'N8N_CRED_GOOGLE_SHEETS_ID', ...(bridge ? ['N8N_CRED_AI_BRIDGE_ID', 'AI_BRIDGE_PORT'] : ['N8N_CRED_ANTHROPIC_ID']),
  ]);

  const config = loadConfig({ bookingUrl: env.BOOKING_URL, sheetId: env.GOOGLE_SHEET_ID });
  const prompts = loadPrompts();
  const codeValues = {
    CONFIG_JSON: JSON.stringify(config),
    SYSTEM_PROMPT_JSON: JSON.stringify(prompts.system.trim()),
    USER_TEMPLATE_JSON: JSON.stringify(prompts.userTemplate),
    SCHEMA_JSON: JSON.stringify(prompts.schema),
    N8N_BASE_URL_JSON: JSON.stringify(env.N8N_BASE_URL.replace(/\/+$/, '')),
  };
  const scalarValues = {
    SITE_ORIGIN: env.SITE_ORIGIN,
    SLACK_WEBHOOK_URL: env.SLACK_WEBHOOK_URL,
    GOOGLE_SHEET_ID: env.GOOGLE_SHEET_ID,
    GOOGLE_SHEET_TAB: env.GOOGLE_SHEET_TAB,
    FROM_HEADER: `"${config.sender.from_display_name}" <${env.SENDER_EMAIL}>`,
    OFFICE_EMAIL: env.SENDER_EMAIL,
    N8N_CRED_SMTP_ID: env.N8N_CRED_SMTP_ID,
    N8N_CRED_GOOGLE_SHEETS_ID: env.N8N_CRED_GOOGLE_SHEETS_ID,
    // AI_MODE=bridge sends the request to the local bridge (Pro plan); api sends it to Anthropic.
    AI_URL: bridge ? `http://host.docker.internal:${env.AI_BRIDGE_PORT}/v1/messages` : 'https://api.anthropic.com/v1/messages',
    AI_CRED_ID: bridge ? env.N8N_CRED_AI_BRIDGE_ID : env.N8N_CRED_ANTHROPIC_ID,
    AI_CRED_NAME: bridge ? 'AI bridge token' : 'Anthropic API key',
  };

  for (const drill of drills) {
    if (!DRILLS[drill]) throw new Error(`Unknown drill "${drill}". Use: ${Object.keys(DRILLS).join(', ')}.`);
    DRILLS[drill](scalarValues, { drillSmtpId });
  }

  const outputs = {};
  for (const [name, outFile] of Object.entries(WORKFLOWS)) {
    let workflow = JSON.parse(read(`workflows/${name}.template.json`));
    for (const node of workflow.nodes) {
      const match = /^%%CODE:([a-z-]+)%%$/.exec(node.parameters?.jsCode ?? '');
      if (!match) continue;
      if (!CODE_NODES[match[1]]) throw new Error(`Unknown code entry ${match[1]} in node "${node.name}".`);
      node.parameters.jsCode = inlineCode(match[1], codeValues);
      syntaxCheck(match[1], node.parameters.jsCode);
    }
    // The error workflow's ID is only known at deploy time; deploy.mjs sets it.
    if (workflow.settings?.errorWorkflow === '%%ERROR_WORKFLOW_ID%%') delete workflow.settings.errorWorkflow;
    workflow = mapStrings(workflow, (text) => replaceTokens(text, scalarValues));
    const leftover = JSON.stringify(workflow).match(/%%[A-Z0-9_:a-z-]+%%/);
    if (leftover) throw new Error(`Unfilled placeholder ${leftover[0]} in ${name}.`);
    mkdirSync(path('build'), { recursive: true });
    writeFileSync(path(outFile), `${JSON.stringify(workflow, null, 2)}\n`);
    outputs[name] = workflow;
  }
  return { endpoint, workflows: outputs, aiMode: bridge ? 'bridge' : 'api', drills };
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const { values: args } = parseArgs({ options: { 'site-only': { type: 'boolean', default: false } } });
  try {
    const result = build({ siteOnly: args['site-only'] });
    console.log(`Wrote site/config.js (form posts to ${result.endpoint})`);
    if (result.workflows) {
      for (const [name, wf] of Object.entries(result.workflows)) {
        const codeNodes = wf.nodes.filter((n) => n.type === 'n8n-nodes-base.code').length;
        console.log(`Wrote ${WORKFLOWS[name]}: ${wf.nodes.length} nodes, ${codeNodes} Code nodes syntax-checked`);
      }
      console.log(`AI step goes to: ${result.aiMode === 'bridge' ? 'the local AI bridge (Pro plan)' : 'the Anthropic API'}`);
    }
  } catch (err) {
    console.error(err.message);
    process.exit(1);
  }
}
