// Build (spec Section 9.7): injects config, prompts, code and secrets into build/*.json and writes
// site/config.js. `npm run build -- --site-only` writes only site/config.js.
// The workflow part arrives in Phase 5.
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { parseArgs } from 'node:util';
import { readEnv } from './lib/env.mjs';

const { values: args } = parseArgs({ options: { 'site-only': { type: 'boolean', default: false } } });
const env = readEnv();

const required = args['site-only'] ? ['N8N_BASE_URL'] : ['N8N_BASE_URL'];
const missing = required.filter((key) => !(env[key] ?? '').trim());
if (missing.length > 0) {
  console.error(`Missing in .env: ${missing.join(', ')}`);
  process.exit(1);
}

function writeSiteConfig() {
  const endpoint = `${env.N8N_BASE_URL.replace(/\/+$/, '')}/webhook/lead-intake`;
  const path = fileURLToPath(new URL('../site/config.js', import.meta.url));
  writeFileSync(path, `// Generated by scripts/build.mjs from .env. Do not edit.\nwindow.LEAD_ENDPOINT = ${JSON.stringify(endpoint)};\n`);
  console.log(`Wrote site/config.js (form posts to ${endpoint})`);
}

writeSiteConfig();
if (!args['site-only']) {
  console.error('The workflow build is added in Phase 5. For now use: npm run build -- --site-only');
  process.exit(1);
}
